name: Secrets
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - runs: echo "${PASSWORD}"
      - runs: echo "${PASSWORD:0:1} ${PASSWORD#?}" # マスクされない
